# CloudFormation template
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to deploy self-driving car application

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      Tags:
        - Key: Name
          Value: Self-Driving-Car
